name: Workflow
on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: composer install
      - name: Install Faker
        run: composer require fzaninotto/Faker
      - name: Install REST
        run: composer require --dev codeception/module-rest
      - name: Run chromedriver
        run: nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &
      - name: Run test cases
        run: php vendor/bin/codecept run functional --steps -vvv --xml
      - name: SUPRISE
        run: echo THANKS KOLESA UPGRADE!!!
      - name: JUnit Report Action
        if: always()
        uses: mikepenz/action-junit-report@v2.4.2
        with:
          report_paths: 'tests/_output/report.xml'
